Switch from direnv to zsh hooks

diff --git a/shell/zsh/zshrc b/shell/zsh/zshrc
--- a/shell/zsh/zshrc
+++ b/shell/zsh/zshrc
@@ -67,12 +67,13 @@ fi
 
 
 # load aliases
-. $DOTFILES_DIR/.direnv/functions_config
-. $DOTFILES_DIR/.direnv/aliases_config
+# . $DOTFILES_DIR/.direnv/functions_config
+# . $DOTFILES_DIR/.direnv/aliases_config
 
 # load commands
-export PATH="$DOTFILES_DIR/.direnv/commands:$PATH"
+# export PATH="$DOTFILES_DIR/.direnv/commands:$PATH"
 
+source $DOTFILES_DIR/shell/zsh/lib.zsh
 
 if ! check_command git FATAL ; then
   return -1
@@ -85,6 +86,7 @@ fi
 if [ ! -f $HOME/dotfiles/.tag_installed_apt ] && check_command apt ; then
   echo "-------------------------------------------------"
   echo "Attempting to install packages .."
+#    direnv \
   sudo apt-get install -y \
     ripgrep \
     fzf \
@@ -96,7 +98,6 @@ if [ ! -f $HOME/dotfiles/.tag_installed_apt ] && check_command apt ; then
     exa \
     curl \
     wget \
-    direnv \
     rsync \
     tmux
 
@@ -112,7 +113,7 @@ export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
 check_command rg INFO 0 "Run 'sudo apt-get install ripgrep' to install it."
 check_command fasd
 check_command fzf INFO 0 "Run 'sudo apt-get install fzf' to install it."
-check_command docker INFO 0 "Check the web how to install it"
+# check_command docker INFO 0 "Check the web how to install it"
 check_command nvim INFO 0 "Run 'sudo apt-get install neovim' to install it."
 # check_command make
 check_command tig INFO 0 "Run 'sudo apt-get install tig' to install it."
@@ -137,14 +138,14 @@ check_command wget INFO 0 "Run 'sudo apt-get install wget' to install it."
 # check_command pyenv
 # check_command nvm
 check_command poetry
-check_command direnv INFO 0 "Run 'sudo apt-get install direnv' to install it."
-check_command docker-compose INFO 0 "Run 'sudo apt-get install docker-compose' to install it."
+# $ check_command direnv INFO 0 "Run 'sudo apt-get install direnv' to install it."
+# check_command docker-compose INFO 0 "Run 'sudo apt-get install docker-compose' to install it."
 check_command rsync INFO 0 "Run 'sudo apt-get install rsync' to install it."
 
 
-if ! [ -d $SPACEVIM_CHECK_DIR ]; then
-  echo "INFO: SpaceVim is not installed. Run 'install_spacevim' to install it and run 'SPUpdate' if needed."
-fi
+# if ! [ -d $SPACEVIM_CHECK_DIR ]; then
+#   echo "INFO: SpaceVim is not installed. Run 'install_spacevim' to install it and run 'SPUpdate' if needed."
+# fi
 
 ### Added by Zinit's installer
 if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
@@ -186,8 +187,115 @@ export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 
 # enable direnv
-eval "$(direnv hook zsh)"
+# eval "$(direnv hook zsh)"
 
 echo "-------------------------------------------------"
-echo "INFO: Done loading zsh. Run 's.!' to search for aliases and functions."
+# echo "INFO: Done loading zsh. Run 's.!' to search for aliases and functions."
+echo "INFO: Run 'init_local' to initialize the local env config."
 echo "-------------------------------------------------"
+
+
+# -----------------------------------------------------------------------------
+# setup for enter/exit cd hooks
+# NOTE: changing these require a full shell restart. zreload doesn't do the trick correctly
+# -----------------------------------------------------------------------------
+alias init_local="cp $HOME/dotfiles/example.zsh.local.sh ./.zsh.local.sh"
+
+load_cd_functions_hook() {
+    local cd_functions_script=".zsh.local.sh"
+    # check file exists, is regular file and is readable:
+    if [[ -f "$cd_functions_script" && -r "$cd_functions_script" ]]; then
+        echo "Loading local config .."
+
+        # defaults, to prevent errors in case they were not defined
+        enter_hook() {}
+
+        exit_hook() {}
+
+        # Store the initial state of functions, aliases, and environment variables
+        initial_functions=(echo ${(ok)functions})
+        initial_functions="$initial_functions print_sourced"
+        initial_aliases=(echo ${(ok)aliases})
+
+        # these need to be here, before the parameters, to avoid picking them up as "new"
+        local_functions=""
+        local_aliases=""
+        local_parameters=""
+        initial_parameters=""
+
+        initial_parameters=(echo ${(ok)parameters})
+
+
+        # define the function to print loaded functions, aliases and envs
+        print_sourced() {
+            for func in ${(ok)functions}; do
+                if [[ ! "$initial_functions" == *"$func"* ]]; then
+                    local_functions="$local_functions $func"
+                fi
+            done
+
+            [[ ! -z $local_functions ]] && echo "Loaded functions:$local_functions"
+
+            for alias in ${(ok)aliases}; do
+                if [[ ! "$initial_aliases" == *"$alias"* ]]; then
+                    local_aliases="$local_aliases $alias"
+                fi
+            done
+
+            [[ ! -z $local_aliases ]] && echo "Loaded aliases:$local_aliases"
+
+            for var in ${(ok)parameters}; do
+                if [[ ! "$initial_parameters" == *"$var"* ]]; then
+                    local_parameters="$local_parameters $var"
+                fi
+            done
+
+            [[ ! -z $local_parameters ]] && echo "Loaded variables:$local_parameters"
+        }
+
+        # source the local env script
+        source "$cd_functions_script"
+
+        # print what was loaded
+        print_sourced
+
+        # run the enter hook
+        enter_hook
+
+    fi
+}
+
+# Set up the chpwd hook to call the load_cd_functions function
+autoload -Uz add-zsh-hook
+add-zsh-hook chpwd load_cd_functions_hook
+
+# Define the cleanup function to be called before each prompt
+cleanup_cd_functions_hook() {
+    local current_dir=${PWD}
+
+    # Check if we have moved away from the previous directory
+    # todo: possible improvement would be to extend this check to allow for children to keep the local config. although current impl. works too
+    if [[ "$current_dir" != "$PREV_PWD" ]]; then
+        local cd_functions_script="$PREV_PWD/.zsh.local.sh"
+
+        if [[ -f "$cd_functions_script" && -r "$cd_functions_script" ]]; then
+            echo "Unloading local config .."
+
+            source "$cd_functions_script"
+            exit_hook
+
+            # cleanup own functions
+            unset -f enter_hook
+            unset -f exit_hook
+        fi
+
+        # Update the previous directory
+        export PREV_PWD="$current_dir"
+    fi
+}
+
+# Set up the precmd hook to call the cleanup function
+autoload -Uz add-zsh-hook
+add-zsh-hook precmd cleanup_cd_functions_hook
+
+# -----------------------------------------------------------------------------
